#cloud-config
# vim: syntax=yaml

packages:
  - mariadb-server

write_files:
  - content: |
         hostname=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/hostname | cut -f 1 -d '.')
         localipv4=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/local-ipv4)
         subnet_address=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/local-ipv4 | cut -f 1-3 -d '.')
         cat <<-EOF | mysql
         create user 'wordpressuser'@'$subnet_address.%' identified by 'openstack';
         grant all on wordpressdb.* to 'wordpressuser'@'*';
         flush privileges;
         EOF
         echo "$localipv4 $hostname" >> /etc/hosts
    owner: root:root
    path: /tmp/start_me_up.sh
    permissions: '0700'

runcmd:
  - sh /tmp/start_me_up.sh
